#!/usr/bin/env python3
"""Generate supabase/migrations/031_seed_email_templates.sql from
scripts/email-content/*.json (the rebuilt Kartra emails).

The JSON files are the reviewable source of truth for the seed; the migration
is generated so SQL escaping is never hand-maintained. Rerun after editing any
content file, then apply with scripts/apply-migrations.sh (the ON CONFLICT
upsert makes re-application safe, but note apply-migrations.sh skips files it
has already recorded — bump the filename if you need a re-seed post-launch;
day-to-day edits belong in the HQ portal, not here).

Usage: python3 scripts/generate-email-seed.py
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = REPO_ROOT / "scripts" / "email-content"
OUT = REPO_ROOT / "supabase" / "migrations" / "031_seed_email_templates.sql"


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    rows = []
    for path in sorted(CONTENT_DIR.glob("*.json")):
        t = json.loads(path.read_text())
        blocks_json = json.dumps(t["blocks"], ensure_ascii=False, separators=(",", ":"))
        rows.append(
            "  ({key}, {name}, {subject}, {preheader}, {blocks}::jsonb, {marketing}, {sort}, {delay})".format(
                key=sql_str(t["template_key"]),
                name=sql_str(t["name"]),
                subject=sql_str(t["subject"]),
                preheader=sql_str(t["preheader"]),
                blocks=sql_str(blocks_json),
                marketing="true" if t["is_marketing"] else "false",
                sort=t["sort_order"],
                delay=sql_str(t["delay_label"]),
            )
        )

    sql = f"""-- 031_seed_email_templates.sql
-- GENERATED by scripts/generate-email-seed.py from scripts/email-content/*.json.
-- Do not hand-edit; edit the JSON and regenerate. Content is the real Kartra
-- post-course journey (docs/kartra-emails/*.html), rebuilt as blocks for the
-- HQ editor. Upsert keeps re-application safe.
--
-- This is migration 031 — do NOT renumber.

INSERT INTO da_email_templates
  (template_key, name, subject, preheader, blocks, is_marketing, sort_order, delay_label)
VALUES
{",\n".join(rows)}
ON CONFLICT (template_key) DO UPDATE SET
  name = EXCLUDED.name,
  subject = EXCLUDED.subject,
  preheader = EXCLUDED.preheader,
  blocks = EXCLUDED.blocks,
  is_marketing = EXCLUDED.is_marketing,
  sort_order = EXCLUDED.sort_order,
  delay_label = EXCLUDED.delay_label;
"""
    OUT.write_text(sql)
    print(f"wrote {OUT} ({len(rows)} templates)")


if __name__ == "__main__":
    main()
