-- 003_customer_booking_tables.sql
-- da_customers, da_private_clients, da_bookings
-- Reference: docs/PRD-technical.md §4.7 — §4.9

-- da_customers ----------------------------------------------------------------

CREATE TABLE da_customers (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  first_name  TEXT NOT NULL,
  last_name   TEXT NOT NULL,
  email       TEXT NOT NULL UNIQUE,
  phone       TEXT,
  postcode    TEXT
);

COMMENT ON TABLE da_customers IS 'End customers (parents) — upserted on booking. Email is identity key.';

-- da_private_clients ----------------------------------------------------------

CREATE TABLE da_private_clients (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  updated_at     TIMESTAMPTZ DEFAULT NOW(),
  franchisee_id  UUID NOT NULL REFERENCES da_franchisees(id),
  company_name   TEXT NOT NULL,
  contact_name   TEXT,
  contact_email  TEXT,
  contact_phone  TEXT,
  notes          TEXT,
  UNIQUE(franchisee_id, company_name)
);

COMMENT ON TABLE da_private_clients IS 'CRM-lite directory of private clients (corporate/schools) per franchisee.';

-- da_bookings -----------------------------------------------------------------
-- booking_reference format DA-{YYYY}-{franchisee_number:5}-{seq} via
-- next_booking_reference() helper added in 008.

CREATE TABLE da_bookings (
  id                         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at                 TIMESTAMPTZ DEFAULT NOW(),
  updated_at                 TIMESTAMPTZ DEFAULT NOW(),
  booking_reference          TEXT NOT NULL UNIQUE,
  course_instance_id         UUID NOT NULL REFERENCES da_course_instances(id),
  franchisee_id              UUID NOT NULL REFERENCES da_franchisees(id),
  customer_id                UUID NOT NULL REFERENCES da_customers(id),
  private_client_id          UUID REFERENCES da_private_clients(id),
  ticket_type_id             UUID NOT NULL REFERENCES da_ticket_types(id),
  quantity                   INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  total_price_pence          INTEGER NOT NULL CHECK (total_price_pence >= 0),
  discount_code              TEXT,
  discount_amount_pence      INTEGER DEFAULT 0 CHECK (discount_amount_pence >= 0),
  payment_status             TEXT NOT NULL DEFAULT 'pending'
                             CHECK (payment_status IN ('pending', 'paid', 'refunded', 'failed', 'manual')),
  stripe_payment_intent_id   TEXT,
  stripe_checkout_session_id TEXT,
  booking_status             TEXT NOT NULL DEFAULT 'confirmed'
                             CHECK (booking_status IN ('confirmed', 'attended', 'no_show', 'cancelled')),
  cancellation_reason        TEXT,
  refund_amount_pence        INTEGER DEFAULT 0 CHECK (refund_amount_pence >= 0),
  notes                      TEXT
);

COMMENT ON TABLE  da_bookings IS 'Atomic bookings linking customer → ticket type → course instance.';
COMMENT ON COLUMN da_bookings.booking_reference IS 'Format: DA-{YYYY}-{franchisee_number:5}-{seq}. Generated by next_booking_reference().';
