-- 015_franchisee_business_name.sql
-- Adds da_franchisees.business_name, the trading name a franchisee uses
-- publicly (e.g. "Daisy First Aid Sutton", "Daisy First Aid Bath & Bristol").
--
-- Background: Jenni's feedback (May 2026) — the franchisee list and detail
-- views should surface the business name alongside the personal name, and the
-- HQ team needs to edit it when the autogenerated form is wrong.
--
-- Reference: plan §3 "015_franchisee_business_name.sql".
--
-- Backfill lives in scripts/seed-territory-areas.ts (separate agent): joins
-- area names per franchisee using rules:
--   1 area  -> "Daisy First Aid {area}"
--   2 areas -> "Daisy First Aid {a} & {b}"
--   3+      -> "Daisy First Aid {a}, {b} & {c}"
-- HQ can override via the update-franchisee Edge Function (extended in this
-- branch to allow business_name in the column allowlist).

ALTER TABLE da_franchisees
  ADD COLUMN business_name TEXT;

COMMENT ON COLUMN da_franchisees.business_name IS 'Public trading name (e.g. "Daisy First Aid Sutton"). Auto-derived from area names by scripts/seed-territory-areas.ts; HQ-editable thereafter.';
