-- 019_payment_link_storage.sql
--
-- Wave 8 (M2) — Stripe Payment Link storage for private courses.
--
-- Purpose:
--   The create-payment-link Edge Function (8B) generates a Stripe Payment Link
--   on the franchisee's connected account and persists it on the course
--   instance. The URL column (da_course_instances.stripe_payment_link) already
--   exists from migration 002; this migration adds the companion timestamp so
--   the UI can show when a link was last (re)generated and so a future job can
--   expire / refresh stale links.
--
-- Why a timestamp and not a status enum:
--   M2 only needs "was a link generated, and when". Payment lifecycle state
--   (paid / refunded) lives on da_bookings, created by the
--   checkout.session.completed webhook (8C) — never inferred from the link.
--
-- Idempotent: ADD COLUMN IF NOT EXISTS so re-runs are no-ops. Existing rows get
-- NULL (no link generated yet).

ALTER TABLE da_course_instances
  ADD COLUMN IF NOT EXISTS payment_link_created_at TIMESTAMPTZ;

COMMENT ON COLUMN da_course_instances.payment_link_created_at IS
  'When the Stripe Payment Link (stripe_payment_link) was last generated by the '
  'create-payment-link Edge Function (Wave 8B). NULL = no link generated yet.';

-- Partial index on stripe_payment_link.
--   Migration 009 indexed several da_course_instances columns but NOT
--   stripe_payment_link (it was unused until Wave 8). Add a partial index that
--   only covers rows that actually have a link, supporting "courses with a
--   payment link" lookups and the webhook's reconciliation path. Guarded by
--   IF NOT EXISTS so this migration stays a no-op if the index is ever added
--   elsewhere first.
CREATE INDEX IF NOT EXISTS idx_course_instances_payment_link
  ON da_course_instances (stripe_payment_link)
  WHERE stripe_payment_link IS NOT NULL;
